---
title: "Homework 1"
subtitle: "AUTUMN 2024"
author: "WRITE YOUR NAME HERE"
date: "`r Sys.Date()`"
output: pdf_document
header-includes:
    - \usepackage{amsmath, amssymb}
    - \usepackage{setspace, diagbox} 
---
\onehalfspacing

* * * 

### Instructions

- This homework is due in Gradescope on Wednesday Oct 16 by midnight PST. There is a 15 minute grace period and submissions made during this time will not be marked as late. Any work submitted past this period is considered late.  

- Please answer the following questions in the order in which they are posed. \textbf{Be sure to support your work and show your steps.}

- Don't forget to (i) make a local copy of this document for your work and to (ii) knit the document frequently to make sure there are no compilation errors. 

- When you are done, download the PDF file and submit it in Gradescope. \textbf{Do not forget to tag your answers to every sub-part of every question. We will take off 10\% for every part that is not tagged}

* * *


### Exercises 

1. (White chip, blue chip) An urn contains four red chips, three white chips,
and two blue chips. A random sample of size 3 is drawn
without replacement. Let $X$ denote the number of white
chips in the sample and $Y$ the number of blue chips. 


a. The sample space $S$ for this experiment consists of  $\binom{N}{n}$ possible outcomes. Give the values for $N$ and $n$. There is no need to evaluate the answer.  

b. Let $E$ denote the event that we draw 1 white, 1 blue and 1 red chip. How many outcomes does $E$ have? Leave your answer in terms of binomial coefficients, do not simplify it and there is no need to evaluate it.  

    Hint: Use the multiplication rule for counting
    
c. Since the samples are drawn randomly, all the outcomes in $S$ are equally likely and we have that 
$$P(E) = \frac{|E|}{|S|} = \frac{\mbox{Number of outcomes in } E}{\mbox{Number of outcomes in } S}$$
by the equally likely rule. Use this along with your what you have learned from parts a and b to fill in the cell corresponding to $x=1, y=1$ in the table of joint probabilities below. Please leave your answer in terms of the ratio of binomial coefficients, do not evaluate it.

    
    \begin{table}[h]
    \centering
    \caption{Joint PMF for $X$ and $Y$}
    \begin{tabular}{|c|c|c|c|c|} \hline
    \backslashbox{$y$}{$x$} & 0 & 1 & 2 & 3 \\ \hline
    0 &  &  &  &  \\ \hline
    1 & & fill this cell only & & \\ \hline
    2 & & & & \\ \hline
    \end{tabular}
    \end{table}
    
d. Write a generic formula now for the joint PMF $f(x,y)$. Don't forget to specify the $x$ and $y$ values for which your formula holds.
    
2. (Trinomial) Let $U_1,U_2, . . . ,U_{1029}$ be independent
uniformly distributed random variables on the interval $[0,1)$. Let $X$ equal the number of $U_i$ less than
.331, and $Y$ equal the number between .331 and .820.

a. The random variables $X$ and $Y$ follow a trinomial distribution. In other words, $\langle X, Y \rangle \sim Trinom(n, \pi_1, \pi_2)$. What are $n$, $\pi_1$ and $\pi_2$? 

b. Use `dmultinom` to calculate the probability of observing $X = 354, Y = 492$. Be sure to show your code in a code chunk and report the probability in a complete sentence using inline code. 
   
c. How many observations should you expect to generate between .331 and .820? With what standard deviation? Be sure to show your code and results. Also state the marginal distribution of $Y$ before launching into calculations.
   
3. (Marginal PMF) Let $X$ and $Y$ be discrete random variables with joint PMF 
$$f(x, y) = \left(\frac{\lambda}{2} \right)^{y} \frac{e^{-\lambda}}{x! \:(y-x)!}$$

    where $x$ and $y$ are (non-negative) integers and $0 \leq x \leq y$. That is, $x, y = 0, 1, 2, 3, \dots$ but with the constraint $0 \leq x \leq y$.

    Determine $f_2(y)$, the marginal distribution of $Y$. Is this a familiar distribution? Show the steps.
   
    *Hint*: you will need to use the Binomial theorem with a = 1 and b = 1 to perform the summation over $x$. 

4. (Hierarchical model) Suppose a player is equally likely to have 4, 5 or 6 at-bats (opportunities to bat) in a baseball game. If $X$ is the number of opportunities to bat, then we are assuming that
$$f_X(x) = P(X = x) = \frac{1}{3}, \ \ \ x = 4, 5, 6.$$
Given that a player has $X = x$ opportunities to bat, suppose the random variable $Y$ denoting the number of hits is a binomial random variable with size $x$ and probability of success $\pi=0.3$. That is 
$$f(y|x) = P(Y = y | X = x) = dbinom(y, \:size = x, \:prob = 0.3).$$
 
a. Fill in the numbers for the joint PMF, $f(x,y) = P(X = x, Y = y)$ in the cells indicated by (i) -- (v) only. Also fill in the number for the marginal PMF $f_2(y)$ in the cell indicated by (vi). Give a brief explanation of your calculations below the table so we know you are not just guessing.

    Hint: you can use inline code within each cell to calculate the corresponding probability

\begin{table}[h]
\centering
\begin{tabular}{||c|c|c|c|c|c|c|c||} \hline
\backslashbox{$x$}{$y$} & 0 & 1 & 2 & 3 & 4 & 5 & 6  \\ \hline
4 & \hspace*{0.2in} & \hspace*{0.2in} & (i) & \hspace*{0.2in}& (ii) & (iii) & \\ \hline \hline
5 & & & (iv) & & & &  \\ \hline  \hline
6 & & & (v) & & & &   \\ \hline \hline
$f_2(y)$ & & & (vi) & & & & \\ \hline
\end{tabular}
\end{table}


b. Calculate $P(X = 5 | Y = 2)$ using R as a calculator.  Be sure to show your code and answer.

   
